const employees = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    password: "123",
    tasks: [
      {
        title: "UI Wireframe Design",
        description: "Create wireframes for the new dashboard page",
        date: "2025-09-01",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client Presentation",
        description: "Prepare slides for the upcoming client meeting",
        date: "2025-09-05",
        category: "Presentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prototype Update",
        description: "Update the interactive prototype with new feedback",
        date: "2025-09-10",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      total: 3,
      active: 1,
      new: 1,
      completed: 1,
      failed: 1,
      pending: 0,
    },
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    password: "123",
    tasks: [
      {
        title: "Database Schema",
        description: "Design schema for employee management system",
        date: "2025-09-02",
        category: "Database",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "API Integration",
        description: "Integrate external payment API into backend",
        date: "2025-09-08",
        category: "Backend",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Unit Testing",
        description: "Write unit tests for authentication module",
        date: "2025-09-12",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Team Meeting",
        description: "Conduct sprint retrospective with the dev team",
        date: "2025-09-14",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      total: 4,
      active: 2,
      new: 1,
      completed: 1,
      failed: 1,
      pending: 0,
    },
  },
  {
    id: 3,
    name: "Michael Lee",
    email: "michael.lee@example.com",
    password: "123",
    tasks: [
      {
        title: "Logo Design",
        description: "Create modern logo concepts for client",
        date: "2025-09-03",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Bug Fixing",
        description: "Fix login page redirect issue",
        date: "2025-09-07",
        category: "Development",
        active: true,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "UI Enhancements",
        description: "Polish buttons and inputs for better UX",
        date: "2025-09-11",
        category: "Frontend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      total: 3,
      active: 2,
      new: 1,
      completed: 1,
      failed: 0,
      pending: 0,
    },
  },
  {
    id: 4,
    name: "Sophia Wilson",
    email: "sophia.wilson@example.com",
    password: "123",
    tasks: [
      {
        title: "Content Writing",
        description: "Write blog article about product updates",
        date: "2025-09-01",
        category: "Content",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "SEO Optimization",
        description: "Improve ranking for landing page keywords",
        date: "2025-09-04",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Email Campaign",
        description: "Schedule weekly promotional emails",
        date: "2025-09-09",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Social Media Posts",
        description: "Design and publish Instagram stories",
        date: "2025-09-15",
        category: "Social Media",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      total: 4,
      active: 2,
      new: 1,
      completed: 1,
      failed: 1,
      pending: 0,
    },
  },
  {
    id: 5,
    name: "David Kumar",
    email: "david.kumar@example.com",
    password: "123",
    tasks: [
      {
        title: "System Monitoring",
        description: "Track server health and uptime",
        date: "2025-09-02",
        category: "IT Support",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Software Update",
        description: "Deploy security patches on client systems",
        date: "2025-09-06",
        category: "IT Support",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Helpdesk Support",
        description: "Resolve user tickets on VPN access",
        date: "2025-09-08",
        category: "Support",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Network Check",
        description: "Run diagnostics on office LAN",
        date: "2025-09-13",
        category: "Networking",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Backup",
        description: "Ensure all critical data is backed up",
        date: "2025-09-15",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      total: 5,
      active: 2,
      new: 1,
      completed: 2,
      failed: 1,
      pending: 0,
    },
  },
];


const admin = 
[{
  "name" : "Abdul Basith",
  "id": 101,
  "email": "admin@example.com",
  "password": "123"
}]


export const  SetLocalStorage =()=>{
    localStorage.setItem('employees' ,JSON.stringify (employees) )
    localStorage.setItem('admin' ,JSON.stringify(admin ) )
}



export const  GetLocalStorage =()=>{
   const employees =  JSON.parse(localStorage.getItem('employees'))
   const admin =  JSON.parse(localStorage.getItem('admin'))
   return {employees , admin}
   
}